name: Testing
on: workflow_dispatch
jobs:
  Android:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6

      - name: Install Haxe Libraries
        run: |
          haxelib install lime --quiet --never --skip-dependencies
          haxelib install openfl --quiet --never --skip-dependencies
          haxelib install flixel --quiet --never --skip-dependencies
          haxelib install hscript --quiet --never --skip-dependencies

      - name: Setup hxcpp Library
        run: haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp.git --quiet --never --skip-dependencies && haxelib run lime rebuild hxcpp

      - name: List Installed Haxe Libraries
        run: haxelib list

      - name: Configure Environment
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_LATEST_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME_11_arm64
          haxelib run lime config ANDROID_SETUP true

      - name: Build
        run: haxelib run lime build android -debug

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: androidBuild
          path: export/android/bin/app/build/outputs/apk/debug
          if-no-files-found: warn
